### ISSUE TITLE
Maps using URLs instead of local storage

### ISSUE THREAD

**Issue by echodreamz** [martinschaible/rspamd-rules#16]
The maps should be able to load over HTTP instead of storing on the file system.

IE...

`
ad_agency_at {
  type = "content";
  filter = "oneline";
  regexp = true;
  one_shot = true;
  map = "https://raw.githubusercontent.com/martinschaible/rspamd-rules/main/maps.d/_ad_agency_at.map";
  score = 20.0;
  symbol = "AD_AGENCY_AT";
  description = "Agencies sending Advertising, Austria";
}
`

Then Rspamd can automatically update the maps once the etag changes.

**Comment by martinschaible** [comment]
Very good idea! I will do this soon. Thanks for the advice.
