### ISSUE TITLE
FP Regex in BASE_BAD_ATTACHMENT_EN 

### ISSUE THREAD

**Issue by spec1re** [martinschaible/rspamd-rules#28]
BASE_BAD_ATTACHMENT_EN (20) [EB-Anforderung.doc]
BASE_BAD_ATTACHMENT_EN (20) [EB-Anforderung.docx]

There is a broken regex for "doc" which is just matching everytihing with it no mather what.

**Comment by martinschaible** [comment]
I'm currently investigate this. I can't find an broken regex right now.

**Comment by spec1re** [comment]
There is another one in BASE_PHRASES_GREETING_DE but it's really hard to guess what is triggering it. 

Maybe add comment to each rule, this would make life much easier eg.

`/grüße.{1,10}mein lieber/i  BASE_PHRASES_GREETING_DE_34:5.0`

**Comment by martinschaible** [comment]
Sorry for the late response. Messages from github landed in the spam folder.

The rule ` /grüße.{1,10}mein lieber/i` is okay, it is a very unusual greeting, in fact malformed german. 

I can't see anything related in rspamd.log.
