### ISSUE TITLE
Eintragungsnachricht - _base_bad_attachment_de.map

### ISSUE THREAD

**Issue by jassi0001** [martinschaible/rspamd-rules#44]
Hi Martin, i have an acritect who receives mails with PDF Attachments named "Eintragunsnachricht.pdf"

The Mulimap in _base_bad_attachment_de.map with Voicemail bounces that messages..... 

How can you sharpen that filter ? What can i do to work around that?

**Comment by martinschaible** [comment]
I removed a rule, which was too strong.
