### ISSUE TITLE
_base_bad_markup.map

### ISSUE THREAD

**Issue by jassi0001** [martinschaible/rspamd-rules#45]
Since two days i notice reject regarding this rule. Seems as if there was a change in the last 5 days.... i set the score down to 0.5 to have mails received....

I do not know which triggered the filter.... Can you please Check?

**Comment by martinschaible** [comment]
This ist the change 5 days ago:

`/<a style=(3d)?"display:none;".{1,10}href=(3d)?.?http:\/\//i`

It triggers "better". May i see an affected mail?

**Comment by jassi0001** [comment]
i tried to get one from the customer but this was not possible, so sorry, no... i will have an eye on that... if i get this filtered again i will give you a follow up. You can close the tickt so far
