### ISSUE TITLE
_base_bad_sender_name_de

### ISSUE THREAD

**Issue by jassi0001** [martinschaible/rspamd-rules#46]
Problem with sender Mail-Adress: microsoftnonprofit@techsoup.org
Was filtered by the named filter. microsoftnonprofit@techsoup.org is a non Profit registration Site....
![image](https://github.com/martinschaible/rspamd-rules/assets/53854561/2fce82fb-4573-4a32-8dc9-9c8b89c95df5)
I think: 

# Which works?
/(kundendienst|support)/n/i
/(kundendienst|support)+$/i

is a little to hard

**Comment by martinschaible** [comment]
Silly me! I need also to add a word boundary for the beginning of the string. I will fix that within the next update.
