### ISSUE TITLE
BASE_PHRASES_SUBJECT_EN (10)

### ISSUE THREAD

**Issue by jassi0001** [martinschaible/rspamd-rules#47]
Hi Martin, eine Frage, warum das hier als Böse erkannt wurde:
BASE_PHRASES_SUBJECT_EN (10) [Ihre Anfrage ANF-SJ-2024000000000 - Grohnder Fährhaus]
und das hier genau so:
BASE_PHRASES_SUBJECT_EN (10) [PaX-Auftragsbestaetigung Nr.10xxxxx Komm : Endkunde]
BASE_PHRASES_SUBJECT_EN (10) [Report Domain: xxx.xxx .de Submitter: aol.com Report-ID: <1712192937.23224>]

von der Sorte habe ich noch einige und es scheint an den eckigen Klammern zu liegen. Da muss im Parser irgendwas falsch sein.

**Comment by jassi0001** [comment]
und das hier genau so:
BASE_PHRASES_SUBJECT_EN (10) [PaX-Auftragsbestaetigung Nr.10xxxxx Komm : Endkunde]

**Comment by martinschaible** [comment]
Hallo

Die eckigen Klammern waren nicht der Grund. Es war ein zu optimistisches Pattern mit langen Nummerfolge. Diese Regel habe ich entfernt.
