### ISSUE TITLE
BASE_BAD_URL_PATH

### ISSUE THREAD

**Issue by jassi0001** [martinschaible/rspamd-rules#48]
Hi Martin, 

die Regel: /\.(com|info|us)\/about\//i ist bei mir angeschlagen, da ein Kunde diese URL wirklich nutzt....
https://www.mofo.com/about/privacy-policy.html
Ich habe den Score erstmal denullt.... wäre aber ein Hinweis darauf, dass die URL wirklich echt ist....

**Comment by martinschaible** [comment]
Hi,

Die Rule habe ich soeben deaktiviert.
