### ISSUE TITLE
virus_en.map - Antivirus Protection

### ISSUE THREAD

**Issue by jassi0001** [martinschaible/rspamd-rules#49]
Hi Martin,

in your Filter "virus_en.map" is a filter regarding "Expired Antivirus Software" where you FIlter for "/anti.?virus.{1,10}protection/i"

This is a little hard, because some of my customers have a Mail Footer, where they write, that they have a solution for "antivirus protection"..... every Mail gets filtered...

So i think you should change that...

**Comment by martinschaible** [comment]
Hi,

This rule is way to hard. I removed it a minute ago. Thanks for the advice.
