### ISSUE TITLE
BASE_PHRASES_SUBJECT_EN suggestion

### ISSUE THREAD

**Issue by alex-c3** [martinschaible/rspamd-rules#53]
Hi,
If I've understood correctly, "..." is filtered by this map (with -> "`/\.\.\.\./i`").

It's something that can be used by some people, although it is indeed rare, it is at least regularly the case in my office, and I wouldn't automatically consider it as spam indication.

I'd understand if you consider it necessary, I can adapt on my side, but at least in french, it's a punctuation that can be used genuinely.

Cheers

**Comment by martinschaible** [comment]
Hi

This rule is a bit dangerous indeed. I remarked it for now.
